project:
  type: website

website:
  search: false
  navbar:
      id: main-navbar 
      type: dark 
      fixed: top 
      left:
        - text: Home
          href: index.qmd
        - text: About Me
          href: index.qmd#about
        - text: Projects
          href: index.qmd#projects
      
  page-footer:
    right: "&copy; 2025, Angela Luo"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false 
  
    include-in-header: 
      - text: |
          <script src="scroll.js"></script> 

execute:
  freeze: auto


